version: "3"

services:
  node:
      build:
          context: .
          dockerfile: docker/node/Dockerfile
      ports:
          - "9090:9090"
      networks:
        - my_network
  varnish:
      build: docker/varnish
      ports:
          - "80:6081"
          - "6085:6085"
      depends_on:
        - node
      environment:
          BACKENDS: "node"
          BACKENDS_PORT: "9090"
          DNS_ENABLED: "true"
          BACKENDS_PROBE_INTERVAL: "3s"
          BACKENDS_PROBE_TIMEOUT: "1s"
          BACKENDS_PROBE_WINDOW: "3"
          BACKENDS_PROBE_THRESHOLD: "2"
          BACKENDS_PROBE_URL: "/check"
          DASHBOARD_USER: "admin"
          DASHBOARD_PASSWORD: "admin"
          DASHBOARD_SERVERS: "varnish"
          DASHBOARD_DNS_ENABLED: "true"
      networks:
          - my_network

networks:
  my_network: